#undef DEBOUNCE
#define DEBOUNCE 10

#undef TAPPING_TERM
#define TAPPING_TERM 150
#define PERMISSIVE_HOLD

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 3000
#define LEADER_TIMEOUT 500 
#define LEADER_PER_KEY_TIMING
#define USB_POLLING_INTERVAL_MS 1