SRC += muse.c #音乐
AUDIO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes # 动态宏
LEADER_ENABLE = yes # leader key
RGBLIGHT_ENABLE = yes # RGB底灯
BOOTMAGIC_ENABLE = full # boot magic
EXTRAKEY_ENABLE = yes # 媒体按键
NKRO_ENABLE = yes # 全键无冲
LAYOUTS = LAYOUT_preonic_2x2u # 双空格layout